import module14
book1=module14.BOOK('Harry Potter','J.Rowling',500,50)
book1.open()
book1.show_status()
book1.next_page()
book1.next_page()
book1.next_page()
book1.next_page()
book1.next_page()
book1.close()
book1.next_page()
